const KEY="mobile_command_center_v2";
const defaults={name:"",budget:0,priorities:["","",""],days:{},tasks:[],events:[],spend:[],notes:{},weekNotes:{}};
let s=load();
function load(){try{return {...structuredClone(defaults),...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{return structuredClone(defaults)}}
function persist(){localStorage.setItem(KEY,JSON.stringify(s))} function save(){persist();render()}
function today(){return new Date().toISOString().slice(0,10)} function current(){let k=today();if(!s.days[k])s.days[k]={p:{},h:{}};return s.days[k]}
function esc(x){return String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function money(x){return "$"+Number(x||0).toLocaleString(undefined,{maximumFractionDigits:0})} function weekStart(){let d=new Date(),n=(d.getDay()+6)%7;d.setDate(d.getDate()-n);d.setHours(0,0,0,0);return d} function iso(d){return d.toISOString().slice(0,10)} function weekDates(){let a=[],st=weekStart();for(let i=0;i<7;i++){let d=new Date(st);d.setDate(st.getDate()+i);a.push(d)}return a}
function navigate(id){document.querySelectorAll(".view,.nav button").forEach(x=>x.classList.remove("on"));document.querySelector("#"+id).classList.add("on");document.querySelector(`.nav button[data-view="${id}"]`)?.classList.add("on");window.scrollTo({top:0,behavior:"smooth"});render()}
function render(){const d=current(),now=new Date(),hr=now.getHours(),hello=hr<12?"Good morning":hr<18?"Good afternoon":"Good evening";document.querySelector("#greeting").textContent=s.name?hello+", "+s.name:hello;document.querySelector("#date").innerHTML=now.toLocaleDateString(undefined,{weekday:"long"})+"<br>"+now.toLocaleDateString(undefined,{month:"short",day:"numeric"});
 document.querySelector("#priorities").innerHTML=s.priorities.slice(0,3).map((p,i)=>`<label class="item ${d.p[i]?"done":""}"><input type="checkbox" data-p="${i}" ${d.p[i]?"checked":""}><div class="itemtext"><input data-pt="${i}" maxlength="80" value="${esc(p)}" placeholder="Priority ${i+1}"></div></label>`).join("");document.querySelectorAll("[data-p]").forEach(x=>x.onchange=()=>{d.p[x.dataset.p]=x.checked;save()});document.querySelectorAll("[data-pt]").forEach(x=>x.onchange=()=>{s.priorities[x.dataset.pt]=x.value.trim();save()});let pc=Object.values(d.p).filter(Boolean).length;document.querySelector("#priorityCount").textContent=pc+" / 3";document.querySelector("#priorityMetric").textContent=pc+"/3";document.querySelector("#priorityWeek").textContent=pc+"/3";
 const open=s.tasks.filter(t=>!t.done),overdue=open.filter(t=>t.due&&t.due<today()).length;document.querySelector("#openTasks").textContent=open.length;document.querySelector("#taskSub").textContent=overdue?overdue+" overdue":"Nothing overdue";let wd=weekDates(),start=iso(wd[0]),end=iso(wd[6]);const ws=s.spend.filter(x=>x.date>=start&&x.date<=end).reduce((a,b)=>a+Number(b.amount||0),0);["#weekSpend","#weekSpend2","#spendTotal"].forEach(id=>document.querySelector(id).textContent=money(ws));document.querySelector("#budgetSub").textContent=s.budget?money(Math.max(s.budget-ws,0))+" remaining of "+money(s.budget):"No spending target";const upcoming=[...s.events].filter(e=>e.date>=today()).sort((a,b)=>(a.date+(a.time||"")).localeCompare(b.date+(b.time||"")));document.querySelector("#eventCount").textContent=upcoming.length;document.querySelector("#eventSub").textContent=upcoming[0]?upcoming[0].title+" · "+upcoming[0].date:"Nothing scheduled";renderNext(upcoming);renderTasks();renderEvents();renderSpend();document.querySelector("#weekRange").textContent=wd[0].toLocaleDateString(undefined,{month:"short",day:"numeric"})+" – "+wd[6].toLocaleDateString(undefined,{month:"short",day:"numeric"});document.querySelector("#weekdays").innerHTML=wd.map(x=>`<div class="wd">${x.toLocaleDateString(undefined,{weekday:"narrow"})}<div class="bubble">${x.getDate()}</div></div>`).join("");document.querySelector("#tasksDone").textContent=s.tasks.filter(t=>t.completed&&t.completed>=start&&t.completed<=end).length;document.querySelector("#weekEvents").textContent=s.events.filter(e=>e.date>=start&&e.date<=end).length;document.querySelector("#dailyNote").value=s.notes[today()]||"";document.querySelector("#weekNote").value=s.weekNotes[start]||"";document.querySelector("#displayName").value=s.name;document.querySelector("#budget").value=s.budget||""}
function renderNext(upcoming){let el=document.querySelector("#nextUp"),a=upcoming.filter(e=>e.date===today()).slice(0,3);el.innerHTML=a.length?a.map(e=>`<div class="event"><div class="event-time">${esc(e.time||"Today")}</div><div><div class="event-title">${esc(e.title)}</div></div></div>`).join(""):'<div class="placeholder">No manual events today. Apple Calendar integration comes next.</div>'}
function renderTasks(){let el=document.querySelector("#tasks");if(!s.tasks.length){el.innerHTML='<div class="placeholder">No tasks yet.</div>';return}el.innerHTML=s.tasks.map((t,i)=>`<div class="item ${t.done?"done":""}"><input type="checkbox" data-task="${i}" ${t.done?"checked":""}><div class="itemtext"><div class="task-title">${esc(t.title)}</div><div class="muted">${t.due?"Due "+t.due:"No due date"}</div></div><button class="mini" data-deltask="${i}">×</button></div>`).join("");document.querySelectorAll("[data-task]").forEach(x=>x.onchange=()=>{let t=s.tasks[x.dataset.task];t.done=x.checked;t.completed=x.checked?today():"";save()});document.querySelectorAll("[data-deltask]").forEach(x=>x.onclick=()=>{s.tasks.splice(+x.dataset.deltask,1);save()})}
function renderEvents(){let el=document.querySelector("#events"),arr=[...s.events].sort((a,b)=>(a.date+(a.time||"")).localeCompare(b.date+(b.time||"")));if(!arr.length){el.innerHTML='<div class="placeholder">No manual events yet.</div>';return}el.innerHTML=arr.map(e=>{let i=s.events.indexOf(e);return `<div class="item"><div class="itemtext"><div class="task-title">${esc(e.title)}</div><div class="muted">${esc(e.date)} ${esc(e.time||"")}</div></div><button class="mini" data-delevent="${i}">×</button></div>`}).join("");document.querySelectorAll("[data-delevent]").forEach(x=>x.onclick=()=>{s.events.splice(+x.dataset.delevent,1);save()})}
function renderSpend(){let el=document.querySelector("#spending"),arr=[...s.spend].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,10);el.innerHTML=arr.length?arr.map(x=>`<div class="money"><span>${esc(x.label)} <span class="muted">${esc(x.date)}</span></span><strong>${money(x.amount)}</strong></div>`).join(""):'<div class="placeholder" style="margin-top:10px">No spending logged.</div>'}
const teams=[
 {key:"browns",teamId:"5",match:"cle",name:"Cleveland Browns",badge:"CLE",sport:"football",league:"nfl",color:"#ff5a1f"},
 {key:"reds",teamId:"17",match:"cin",name:"Cincinnati Reds",badge:"CIN",sport:"baseball",league:"mlb",color:"#c6011f"},
 {key:"osufb",teamId:"194",match:"osu",name:"Ohio State Football",badge:"OSU",sport:"football",league:"college-football",color:"#bb0000"},
 {key:"osubb",teamId:"194",match:"osu",name:"Ohio State Basketball",badge:"OSU",sport:"basketball",league:"mens-college-basketball",color:"#bb0000"},
 {key:"cavs",teamId:"5",match:"cle",name:"Cleveland Cavaliers",badge:"CLE",sport:"basketball",league:"nba",color:"#860038"}
];
function teamMatch(t,c){let a=(c.team?.abbreviation||"").toLowerCase(),id=String(c.team?.id||"");return id===t.teamId||a===t.match}
function eventForTeam(t,e){return e?.competitions?.[0]?.competitors?.some(c=>teamMatch(t,c))}
async function jsonFetch(url){let r=await fetch(url,{cache:"no-store"});if(!r.ok)throw new Error("feed");return r.json()}
async function fetchTeam(t){try{
 let base=`https://site.api.espn.com/apis/site/v2/sports/${t.sport}/${t.league}`;
 let [score,schedule]=await Promise.allSettled([jsonFetch(`${base}/scoreboard`),jsonFetch(`${base}/teams/${t.teamId}/schedule`)]);
 let events=[]; if(score.status==="fulfilled")events.push(...(score.value.events||[])); if(schedule.status==="fulfilled")events.push(...(schedule.value.events||[]));
 let seen=new Set();events=events.filter(e=>e?.id&&!seen.has(e.id)&&seen.add(e.id)&&eventForTeam(t,e));
 let live=events.find(e=>e.status?.type?.state==="in");
 let future=events.filter(e=>e.status?.type?.state==="pre"&&new Date(e.date)>=new Date(Date.now()-60*60*1000)).sort((a,b)=>new Date(a.date)-new Date(b.date))[0];
 let e=live||future||null;
 let teamData=(e?.competitions?.[0]?.competitors||[]).find(c=>teamMatch(t,c))?.team || schedule.value?.team || null;
 return {event:e,logo:teamData?.logo||teamData?.logos?.[0]?.href||"",live:!!live,start:e?new Date(e.date).getTime():Number.MAX_SAFE_INTEGER};
 }catch{return {event:null,logo:"",live:false,start:Number.MAX_SAFE_INTEGER}}
}
async function loadSports(){let box=document.querySelector("#sports"),status=document.querySelector("#sportsStatus");box.innerHTML=teams.map(t=>gameHTML(t,{event:null,logo:"",loading:true})).join("");let rows=await Promise.all(teams.map(async t=>({t,r:await fetchTeam(t)})));rows.sort((a,b)=>(b.r.live-a.r.live)||(a.r.start-b.r.start)||a.t.name.localeCompare(b.t.name));box.innerHTML=rows.map(x=>gameHTML(x.t,x.r)).join("");status.textContent=rows.some(x=>x.r.live)?"Live first · then next up":"Next games"}
function gameHTML(t,r){let e=r?.event,logo=r?.logo||"",badge=logo?`<img src="${esc(logo)}" alt="" onerror="this.parentElement.innerHTML='<span class=teamFallback>${t.badge}</span>'">`:`<span class="teamFallback">${t.badge}</span>`;if(r?.loading)return `<div class="game" style="--team:${t.color}"><div class="teamBadge">${badge}</div><div><div class="gameName">${t.name}</div><div class="gameMeta">Loading next game…</div></div><div></div></div>`;if(!e)return `<div class="game" style="--team:${t.color}"><div class="teamBadge">${badge}</div><div><div class="gameName">${t.name}</div><div class="gameMeta">Next game not yet published</div></div><div></div></div>`;let c=e.competitions?.[0],state=e.status?.type?.state,detail=e.status?.type?.shortDetail||"",mine=c?.competitors?.find(x=>teamMatch(t,x)),opp=c?.competitors?.find(x=>x!==mine),oppName=opp?.team?.displayName||"Opponent TBD";let when=state==="in"?`<span class="live">LIVE</span> · ${esc(detail)}`:new Date(e.date).toLocaleString(undefined,{weekday:"short",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"});let venue=mine?.homeAway==="away"?"at":"vs";let sc=state==="in"?`${mine?.score||0} – ${opp?.score||0}`:"";return `<div class="game" style="--team:${t.color}"><div class="teamBadge">${badge}</div><div><div class="gameName">${t.name}</div><div class="gameMeta">${when} · ${venue} ${esc(oppName)}</div></div><div class="score">${sc}</div></div>`}
document.querySelector("#openSpotify").onclick=()=>{location.href="spotify://";setTimeout(()=>{location.href="https://open.spotify.com"},700)};document.querySelector("#addTask").onclick=()=>{let title=prompt("Task");if(!title)return;let due=prompt("Due date (YYYY-MM-DD), or leave blank","")||"";s.tasks.unshift({title:title.trim(),due,done:false,completed:""});save()};document.querySelector("#addEvent").onclick=()=>{let title=prompt("Event");if(!title)return;let date=prompt("Date (YYYY-MM-DD)",today());if(!date)return;let time=prompt("Time, or leave blank","")||"";s.events.push({title:title.trim(),date,time});save()};document.querySelector("#addSpend").onclick=()=>{let label=prompt("What did you spend on?");if(!label)return;let amount=Number(prompt("Amount","0"));if(!Number.isFinite(amount)||amount<0)return;s.spend.unshift({label:label.trim(),amount,date:today()});save()};document.querySelector("#dailyNote").oninput=e=>{s.notes[today()]=e.target.value;persist()};document.querySelector("#weekNote").oninput=e=>{s.weekNotes[iso(weekStart())]=e.target.value;persist()};document.querySelector("#saveSettings").onclick=()=>{s.name=document.querySelector("#displayName").value.trim();s.budget=Math.max(0,Number(document.querySelector("#budget").value)||0);save();navigate("todayView")};document.querySelectorAll(".nav button").forEach(b=>b.onclick=()=>navigate(b.dataset.view));render();loadSports();
